### ISSUE TITLE
Issues building PDF

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#291]
With sphinx 2.4 in a virtual environment:

```
(venv) [michael@localhost specification]$ make html
sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v2.4.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/michael/dev/cellml/specification/venv/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/michael/dev/cellml/specification/venv/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/michael/dev/cellml/specification/src/conf.py", line 66, in <module>
    manage_index('in')
  File "/home/michael/dev/cellml/specification/src/conf.py", line 36, in manage_index
    os.rename(os.path.abspath(files[0]), os.path.abspath(files[1]))
FileNotFoundError: [Errno 2] No such file or directory: '/home/michael/dev/cellml/specification/src/master_index.rst' -> '/home/michael/dev/cellml/specification/src/index.rst'

make: *** [Makefile:45: html] Error 2
```

**Comment by MichaelClerx** [comment]
See #285
